apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tackle2-hub
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tackle2-hub
    app.kubernetes.io/part-of: tackle2-hub
  name: tackle2-hub
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: tackle2-hub
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: tackle2-hub
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/shawnhurley-tenant/tackle2-hub/tackle2-hub@sha256:c7b0abcf7d8e8ca93904b6d4634dd101277053b6b66f7801e6ceb38616ed21cd
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
